"""OpenAPI schema + Swagger/Redoc UI for the Django backend.

The two UI pages and the favicon are returned as self-contained HTML that
loads everything (Swagger UI, Redoc, favicon) from public CDNs. This
sidesteps Django's staticfiles pipeline entirely, so the docs render
correctly on a read-only serverless filesystem (Vercel) without a
``collectstatic`` step.

The OpenAPI schema itself is still generated by drf_yasg and served from
``/swagger.json`` and ``/swagger.yaml``; the CDN-loaded UIs fetch from
there.
"""

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

# --- Schema generator -----------------------------------------------------
schema_view = get_schema_view(
    openapi.Info(
        title="Moodify Emotion-Based Music API",
        default_version="v1",
        description="REST API for the Moodify Emotion-Based Music App.",
        terms_of_service="https://moodify-emotion-music-app.vercel.app/terms-of-service",
        contact=openapi.Contact(
            email="hoangson091104@gmail.com",
            name="Moodify",
            url="https://moodify-emotion-music-app.vercel.app/",
        ),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

# --- CDN assets -----------------------------------------------------------
_SWAGGER_UI_VERSION = "5.17.14"
_REDOC_VERSION = "2.1.5"
# Music note (U+1F3B5) from the Twemoji set on jsDelivr -- public, stable,
# and matches the app's musical theme. Served as SVG so it scales.
_FAVICON_URL = (
    "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3b5.svg"
)


def swagger_ui(request):
    """Render Swagger UI with all assets loaded from jsDelivr."""
    return HttpResponse(
        f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Moodify API - Swagger</title>
  <link rel="icon" type="image/svg+xml" href="{_FAVICON_URL}">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@{_SWAGGER_UI_VERSION}/swagger-ui.css">
  <style>body {{ margin: 0; background: #fafafa; }}</style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@{_SWAGGER_UI_VERSION}/swagger-ui-bundle.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@{_SWAGGER_UI_VERSION}/swagger-ui-standalone-preset.js"></script>
  <script>
    window.ui = SwaggerUIBundle({{
      url: "/swagger.json",
      dom_id: "#swagger-ui",
      deepLinking: true,
      presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
      layout: "StandaloneLayout",
      persistAuthorization: true,
    }});
  </script>
</body>
</html>
""",
        content_type="text/html",
    )


def redoc_ui(request):
    """Render Redoc with all assets loaded from jsDelivr."""
    return HttpResponse(
        f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Moodify API - Redoc</title>
  <link rel="icon" type="image/svg+xml" href="{_FAVICON_URL}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>body {{ margin: 0; }}</style>
</head>
<body>
  <redoc spec-url="/swagger.json"></redoc>
  <script src="https://cdn.jsdelivr.net/npm/redoc@{_REDOC_VERSION}/bundles/redoc.standalone.js"></script>
</body>
</html>
""",
        content_type="text/html",
    )


def favicon(request):
    """Bounce /favicon.ico to the CDN-hosted SVG so browsers stop 404ing."""
    return HttpResponseRedirect(_FAVICON_URL)


urlpatterns = [
    # JSON / YAML schema -- what the UIs above fetch.
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path("swagger/", swagger_ui, name="schema-swagger-ui"),
    path("redoc/", redoc_ui, name="schema-redoc"),
    path("favicon.ico", favicon, name="favicon"),
]
