# External Secrets Operator Installation
# Syncs secrets from external secret managers (AWS Secrets Manager, Vault, etc.)

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
# Install using Helm
apiVersion: batch/v1
kind: Job
metadata:
  name: install-external-secrets-operator
  namespace: external-secrets
spec:
  template:
    spec:
      serviceAccountName: external-secrets-installer
      containers:
      - name: helm
        image: alpine/helm:3.13.0
        command:
        - /bin/sh
        - -c
        - |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update
          helm install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --version 0.9.11 \
            --set installCRDs=true \
            --set webhook.port=9443 \
            --wait
      restartPolicy: OnFailure
  backoffLimit: 3

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-installer
  namespace: external-secrets

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: external-secrets-installer
  namespace: external-secrets

---
# AWS Secrets Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: moodify-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: moodify-backend-sa

---
# External Secret for Moodify Backend
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: moodify-backend-secrets
  namespace: moodify-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: moodify-secrets
    creationPolicy: Owner

  data:
    # Database credentials
    - secretKey: DB_PASSWORD
      remoteRef:
        key: moodify/production/database
        property: password

    - secretKey: DB_USERNAME
      remoteRef:
        key: moodify/production/database
        property: username

    # Redis credentials
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: moodify/production/redis
        property: password

    # Application secrets
    - secretKey: JWT_SECRET
      remoteRef:
        key: moodify/production/app
        property: jwt_secret

    - secretKey: SESSION_SECRET
      remoteRef:
        key: moodify/production/app
        property: session_secret

    # Spotify API
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: moodify/production/spotify
        property: client_id

    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: moodify/production/spotify
        property: client_secret

---
# ClusterSecretStore for cluster-wide secrets
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-cluster
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets

---
# IAM Role for External Secrets (IRSA)
# This should be created via Terraform with proper permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/moodify-production-external-secrets
